# Generated by Django 3.0.3 on 2020-05-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygrometer', '0004_auto_20200518_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='prioridad',
            field=models.IntegerField(verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipoIndicador',
            field=models.CharField(max_length=20, verbose_name='tipoIndicador'),
        ),
    ]
