# Generated by Django 3.0.3 on 2020-05-19 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hygrometer', '0005_auto_20200518_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(verbose_name='cedula')),
                ('nombre', models.CharField(max_length=30)),
                ('actividad', models.CharField(max_length=30)),
                ('estrato', models.IntegerField(verbose_name='estrato')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Hygrometer',
            new_name='Luminosity',
        ),
        migrations.DeleteModel(
            name='Indicador',
        ),
    ]
